# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Delploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary
    - name: Deploy with rsync
      run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/
    - name: build and start
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: docker-compose up -d --no-deps --build
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
    
        
