# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Delploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: app
        path: ./
    
    
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build, ]
    steps:
    - name: Download csp artifacts
      uses: actions/download-artifact@v1
      with:
        name: app
    - name: Copy host via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
      with:
        source: "app/*"
        target: "/tmp"
        strip_components: 1
        rm: false
        overwrite: true

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        USERNAME: deploy
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /tmp
          docker-compose up -d --no-deps --build
    
    
        
